[package]
name = "noita-utility-box"
description = "A collection of memory-reading utilities for the game Noita"
version = "0.2.0"
license = "MIT"
edition = "2021"

[dependencies]
anyhow = "1"
color-eyre = "0.6"
derive_more = { version = "1", default-features = false, features = [
    "debug",
    "deref",
    "display",
] }
eframe = { version = "0.29", features = ["persistence", "ron", "wgpu"] }
egui-modal = "0.5"
egui_extras = "0.29"
fastrand = "2"
futures = "0.3"
iced-x86 = "1"
lazy-regex = "3"
memchr = "2"
obws = { version = "0.13", features = ["events"] }
rayon = "1"
read-process-memory = "0.1"
reqwest = { version = "0.12", features = ["json"] }
serde = { version = "1", features = ["derive"] }
smart-default = "0.7"
strfmt = "0.2"
strum = { version = "0.26", features = ["derive"] }
sysinfo = "0.32"
thiserror = "1"
tokio = { version = "1", features = ["rt-multi-thread"] }
tracing = "0.1"
tracing-appender = "0.2"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zerocopy = { version = "0.8", default-features = false, features = [
    "alloc",
    "derive",
] }

[build-dependencies]
winresource = { version = "0.1", default-features = false }
