[package]
name = "noita-counter"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
bytemuck = { version = "1", features = ["derive"] }
clap = { version = "4", features = ["derive"] }
process-memory = "0.5"
strfmt = "0.2"
sysinfo = "0.31"
toml = "0.8"
