# Address of the tree map which contains KEY_VALUE_STATS,
# of which progress_ending0 and progress_ending1 add up to the number of wins,
# which is then added to the format as a `wins` variable
stats-map = 0x01206938

# Read arbitrary global unsigned 4-byte integers from these locations
# The keys are then available in the format string
[u32]
seed = 0x01202fe4
ng-plus-count = 0x01203004

# Those 3 are from the GlobalStats global
deaths = 0x01206ad8
streak = 0x0120694c
streak-pb = 0x01206a14
