name: Release

on:
  push:
    tags:
      - v*.*.*

jobs:
  test:
    name: Build and Release
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@v14
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - uses: actions/checkout@v4

      - name: Build
        id: build
        run: |
          echo "CI_RELEASE_VERSION=\"${GITHUB_REF_NAME#v}\"" >> env-input.toml
          echo "VERSION=${GITHUB_REF_NAME#v}" >> $GITHUB_OUTPUT
          nix build . .#windows .#linux .#deb --override-input build-env "file+file://$PWD/env-input.toml"

      - name: Finalize artifacts
        run: |
          ./.github/workflows/finalize-artifacts.sh

          gzip noita-utility-box-linux-generic.tar
          zip -r noita-utility-box-windows.zip noita-utility-box.exe

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: true
          files: |
            noita-utility-box-windows.zip
            noita-utility-box.deb
            noita-utility-box-linux-generic.tar.gz
